#!/usr/bin/env bash
# test-skill.sh — Regression suite for the single-branch-development hooks bundle.
#
# Tests: track-preflight, track-reconcile, track-guard, track-evidence (producer),
#        track-evidence-gate, track-meter, track-trace, track-report, track-sentinel,
#        track-notify, structural integrity. Includes a producer->gate end-to-end contract
#        so the evidence record is generated by track-evidence.sh, never hand-written.
#        13 suites · 104 total · 103 passed · 0 failed · 1 skipped (2026-07-11)
#
# Usage:
#   bash .github/skills/single-branch-development/tests/test-skill.sh
#   bash tests/test-skill.sh          # from inside single-branch-development/ dir
#
# Requirements: bash, jq, git (gh auth bypassed via PREFLIGHT_REQUIRE_GH=0).
# Side-effects: temp branch + temp runs/ dir; cleaned up on exit.
# Exit: 0 = all passed, 1 = one or more failures.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$SCRIPT_DIR/../scripts"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
cd "$REPO_ROOT"

GUARD="$SCRIPTS_DIR/track-guard.sh"
PREFLIGHT="$SCRIPTS_DIR/track-preflight.sh"
RECONCILE="$SCRIPTS_DIR/track-reconcile.sh"
EVIDENCE="$SCRIPTS_DIR/track-evidence.sh"
EVIDENCE_GATE="$SCRIPTS_DIR/track-evidence-gate.sh"
METER="$SCRIPTS_DIR/track-meter.sh"
TRACE="$SCRIPTS_DIR/track-trace.sh"
NOTE="$SCRIPTS_DIR/track-note.sh"
SENTINEL="$SCRIPTS_DIR/track-sentinel.sh"
NOTIFY="$SCRIPTS_DIR/track-notify.sh"
TOKENS="$SCRIPTS_DIR/track-tokens.sh"
for s in "$GUARD" "$PREFLIGHT" "$RECONCILE" "$EVIDENCE" "$EVIDENCE_GATE" \
         "$METER" "$TRACE" "$NOTE" "$SENTINEL" "$NOTIFY" "$TOKENS"; do
  [ -x "$s" ] || chmod +x "$s"
done
INSTALL_HOOKS="$SCRIPTS_DIR/install-hooks.sh"
[ -x "$INSTALL_HOOKS" ] || chmod +x "$INSTALL_HOOKS"

# ---------------------------------------------------------------------------
# Harness
# ---------------------------------------------------------------------------
PASS=0; FAIL=0; SKIP=0; FAILURES=""
pass() { PASS=$((PASS+1)); printf '  OK    %s\n' "$1"; }
fail() { FAIL=$((FAIL+1)); printf '  FAIL  %s\n' "$1"; FAILURES="$FAILURES\n  - $1"; }
skip() { SKIP=$((SKIP+1)); printf '  SKIP  %s\n' "$1"; }
section() { printf '\n--- %s ---\n' "$1"; }

assert_deny() {
  local desc="$1" hook="$2" json="$3"; shift 3
  local result
  result=$(printf '%s' "$json" | env "$@" bash "$hook" 2>&1) || true
  if printf '%s' "$result" | grep -qE '"deny"|"block"'; then pass "$desc"
  else fail "$desc (got: $(printf '%s' "$result" | head -c 120))"; fi
}
assert_allow() {
  local desc="$1" hook="$2" json="$3"; shift 3
  local result
  result=$(printf '%s' "$json" | env "$@" bash "$hook" 2>&1) || true
  if printf '%s' "$result" | grep -qE '"deny"|"block"'; then
    fail "$desc (expected allow, got: $(printf '%s' "$result" | head -c 120))"
  else pass "$desc"; fi
}

# ---------------------------------------------------------------------------
# Temp state
# ---------------------------------------------------------------------------
TMPDIR_RUNS="$(mktemp -d)"
ORIG_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo detached)"
TEST_BRANCH="test/sbd-skill-$(date +%s)"
SCRATCH_FILES=()
RUN1_ID=""

cleanup() {
  git checkout "$ORIG_BRANCH" --quiet 2>/dev/null || true
  git branch -D "$TEST_BRANCH" --quiet 2>/dev/null || true
  for f in "${SCRATCH_FILES[@]:-}"; do
    git rm --cached "$f" --quiet 2>/dev/null || true; rm -f "$f"; done
  rm -rf "$TMPDIR_RUNS"
}
trap cleanup EXIT
git checkout -b "$TEST_BRANCH" --quiet 2>/dev/null

# Fingerprint matching evidence-gate/evidence exactly (HEAD + diff + untracked)
current_fingerprint() {
  local hc; command -v shasum >/dev/null 2>&1 && hc=shasum || hc=sha1sum
  { git rev-parse HEAD 2>/dev/null || echo no-head
    git diff HEAD 2>/dev/null || true
    local u; u="$(git ls-files --others --exclude-standard 2>/dev/null || true)"
    if [ -n "$u" ]; then
      printf '%s\n' "$u"; printf '%s\n' "$u" | git hash-object --stdin-paths 2>/dev/null || true
    fi
  } | $hc | cut -d' ' -f1
}

ABS="${REPO_ROOT}/"

# ---------------------------------------------------------------------------
# SUITE 1 -- track-preflight.sh
# ---------------------------------------------------------------------------
section "track-preflight.sh"

result=$(TRACK_ID=tst-setup TASKS="T001-T005" TRACK_BASE_REF=main \
         PREFLIGHT_REQUIRE_GH=0 RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" 2>&1)
if printf '%s' "$result" | grep -q '"mode":"start"'; then
  pass "preflight: fresh start -> mode=start + RUN_ID minted"
  RUN1_ID=$(printf '%s' "$result" | grep -o '"run_id":"[^"]*"' | cut -d'"' -f4)
else fail "preflight: fresh start -> mode=start + RUN_ID minted"; fi

TRACK_ID=tst-setup TASKS="T001-T005" TRACK_BASE_REF=main \
PREFLIGHT_REQUIRE_GH=0 RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" --commit >/dev/null 2>&1
ls "$TMPDIR_RUNS"/*.dispatch >/dev/null 2>&1 \
  && pass "preflight: --commit persists .dispatch breadcrumb" \
  || fail "preflight: --commit persists .dispatch breadcrumb"

# breadcrumb records the confirmed scope/toolchain/floor, not just identity
rm -f "$TMPDIR_RUNS"/*.dispatch
TRACK_ID=tst-stamp TASKS="T001" TRACK_BASE_REF=main PREFLIGHT_REQUIRE_GH=0 \
  TRACK_ALLOWED_PREFIXES="backend-go/:frontend/" PREFLIGHT_REQUIRE_TOOLCHAIN="git,jq" \
  TRACK_REQUIRED_EVIDENCE="go-test,py" RUNS_DIR="$TMPDIR_RUNS" \
  bash "$PREFLIGHT" --commit >/dev/null 2>&1
stamp_file=$(ls "$TMPDIR_RUNS"/*tst-stamp*.dispatch 2>/dev/null | head -1)
if [ -n "$stamp_file" ] && jq -e '(.allowed_prefixes | index("backend-go/") != null) and .scope_set == true and (.require_toolchain | index("jq") != null) and (.required_evidence | index("go-test") != null) and .evidence_floor_set == true' "$stamp_file" >/dev/null 2>&1; then
  pass "preflight: --commit stamps confirmed scope/toolchain/floor into breadcrumb"
else
  fail "preflight: --commit stamps confirmed scope/toolchain/floor into breadcrumb"
fi

# --complete stamps completed_utc + numeric duration_secs (write-once) at PR handoff
rm -f "$TMPDIR_RUNS"/*.dispatch
TRACK_ID=tst-done TASKS="T001" TRACK_BASE_REF=main PREFLIGHT_REQUIRE_GH=0 \
  RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" --commit >/dev/null 2>&1
TRACK_ID=tst-done TRACK_BASE_REF=main PREFLIGHT_REQUIRE_GH=0 \
  RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" --complete >/dev/null 2>&1
done_file=$(ls "$TMPDIR_RUNS"/*tst-done*.dispatch 2>/dev/null | head -1)
if [ -n "$done_file" ] && jq -e '(.completed_utc | type == "string" and . != "") and (.duration_secs | type == "number")' "$done_file" >/dev/null 2>&1; then
  pass "preflight: --complete stamps completed_utc + numeric duration_secs"
else
  fail "preflight: --complete stamps completed_utc + numeric duration_secs"
fi
# write-once: a second --complete must not overwrite the original finish time
first_done=$(jq -r '.completed_utc' "$done_file" 2>/dev/null)
TRACK_ID=tst-done TRACK_BASE_REF=main PREFLIGHT_REQUIRE_GH=0 \
  RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" --complete >/dev/null 2>&1
[ "$(jq -r '.completed_utc' "$done_file" 2>/dev/null)" = "$first_done" ] \
  && pass "preflight: --complete is write-once (resume can't clobber finish time)" \
  || fail "preflight: --complete is write-once (resume can't clobber finish time)"
rm -f "$TMPDIR_RUNS"/*.dispatch
TRACK_ID=tst-setup TASKS="T001-T005" TRACK_BASE_REF=main \
  PREFLIGHT_REQUIRE_GH=0 RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" --commit >/dev/null 2>&1

result=$(TRACK_ID=tst-setup TRACK_BASE_REF=main PREFLIGHT_REQUIRE_GH=0 \
         RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" 2>&1)
printf '%s' "$result" | grep -q '"mode":"resume"' \
  && pass "preflight: same slug -> RESUME mode" || fail "preflight: same slug -> RESUME mode"

result2=$(TRACK_ID=tst-other TRACK_BASE_REF=main PREFLIGHT_REQUIRE_GH=0 \
          RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" 2>&1)
printf '%s' "$result2" | grep -q '"mode":"start"' \
  && pass "preflight: different slug -> fresh START" \
  || fail "preflight: different slug -> fresh START"

RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" 2>/dev/null \
  && fail "preflight: missing TRACK_ID -> hard-fail exit 1" \
  || pass "preflight: missing TRACK_ID -> hard-fail exit 1"

result=$(TRACK_ID=tst-scope TRACK_BASE_REF=main PREFLIGHT_REQUIRE_GH=0 \
         TRACK_ALLOWED_PREFIXES="backend-go/:frontend/" RUNS_DIR="$TMPDIR_RUNS" \
         bash "$PREFLIGHT" 2>/dev/null)
printf '%s' "$result" | jq -e '.scope_set == true and (.allowed_prefixes | index("backend-go/") != null)' >/dev/null 2>&1 \
  && pass "preflight: writable scope surfaced in JSON" \
  || fail "preflight: writable scope surfaced in JSON"

# TRACK_BRANCH: custom name wins; absent -> derived from the track slug; invalid -> hard-fail
result=$(TRACK_ID=tst-br TRACK_BRANCH="feat/custom-name" TRACK_BASE_REF=main PREFLIGHT_REQUIRE_GH=0 \
         RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" 2>/dev/null)
printf '%s' "$result" | jq -e '.branch == "feat/custom-name"' >/dev/null 2>&1 \
  && pass "preflight: TRACK_BRANCH override sets custom branch name" \
  || fail "preflight: TRACK_BRANCH override sets custom branch name"

result=$(TRACK_ID=tst-slug TRACK_BASE_REF=main PREFLIGHT_REQUIRE_GH=0 \
         RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" 2>/dev/null)
printf '%s' "$result" | jq -e '.branch == "tst-slug"' >/dev/null 2>&1 \
  && pass "preflight: no TRACK_BRANCH -> branch derived from track slug" \
  || fail "preflight: no TRACK_BRANCH -> branch derived from track slug"

TRACK_ID=tst-badbr TRACK_BRANCH="bad branch~name" TRACK_BASE_REF=main PREFLIGHT_REQUIRE_GH=0 \
  RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" >/dev/null 2>&1 \
  && fail "preflight: invalid TRACK_BRANCH -> hard-fail exit 1" \
  || pass "preflight: invalid TRACK_BRANCH -> hard-fail exit 1"

result=$(TRACK_ID=tst-noscope TRACK_BASE_REF=main PREFLIGHT_REQUIRE_GH=0 \
         RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" 2>/dev/null)
printf '%s' "$result" | jq -e '.scope_set == false' >/dev/null 2>&1 \
  && pass "preflight: unset scope -> scope_set=false (guard fails closed)" \
  || fail "preflight: unset scope -> scope_set=false (guard fails closed)"

result=$(TRACK_ID=tst-tc TRACK_BASE_REF=main PREFLIGHT_REQUIRE_GH=0 \
         PREFLIGHT_REQUIRE_TOOLCHAIN="git,jq" TRACK_REQUIRED_EVIDENCE="go-test,py" \
         RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" 2>/dev/null)
printf '%s' "$result" | jq -e '.toolchain_set == true and (.require_toolchain | index("git") != null) and .evidence_floor_set == true and (.required_evidence | index("py") != null)' >/dev/null 2>&1 \
  && pass "preflight: toolchain + evidence floor surfaced in JSON" \
  || fail "preflight: toolchain + evidence floor surfaced in JSON"

result=$(TRACK_ID=tst-nofloor TRACK_BASE_REF=main PREFLIGHT_REQUIRE_GH=0 \
         RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" 2>/dev/null)
printf '%s' "$result" | jq -e '.evidence_floor_set == false and .toolchain_set == false' >/dev/null 2>&1 \
  && pass "preflight: unset floor/toolchain -> *_set=false (weaker gate flagged)" \
  || fail "preflight: unset floor/toolchain -> *_set=false (weaker gate flagged)"

# ---------------------------------------------------------------------------
# SUITE 2 -- track-reconcile.sh
# ---------------------------------------------------------------------------
section "track-reconcile.sh"

if [ -n "$RUN1_ID" ]; then
  printf '{"evidence":[{"kind":"go-test","cmd":"go test","response":"ok","fingerprint":"0000000000000000000000000000000000000001"}]}' \
    > "$TMPDIR_RUNS/$RUN1_ID.json"
  result=$(printf '{}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" TRACK_BASE_REF=main \
           TRACK_REQUIRED_EVIDENCE="go-test" bash "$RECONCILE" 2>/dev/null)
  printf '%s' "$result" | jq -e '.evidence.stale | index("go-test") != null' >/dev/null 2>&1 \
    && pass "reconcile: stale evidence identified" \
    || fail "reconcile: stale evidence identified"

  result=$(printf '{}' | TRACK_ID=tst-setup RUNS_DIR="$TMPDIR_RUNS" \
           TRACK_BASE_REF=main bash "$RECONCILE" 2>/dev/null)
  printf '%s' "$result" | jq -e '.run_id != null' >/dev/null 2>&1 \
    && pass "reconcile: RUN_ID auto-recovered from breadcrumb" \
    || fail "reconcile: RUN_ID auto-recovered from breadcrumb"

  RECON_FP=$(printf '{}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" \
             TRACK_BASE_REF=main bash "$RECONCILE" 2>/dev/null | jq -r '.fingerprint')
  GATE_FP=$(current_fingerprint)
  [ "$RECON_FP" = "$GATE_FP" ] \
    && pass "reconcile: fingerprint == evidence-gate (bug-regression)" \
    || fail "reconcile: fingerprint mismatch (reconcile=$RECON_FP gate=$GATE_FP)"
else
  skip "reconcile: stale evidence (no RUN1_ID)"; skip "reconcile: auto-recovery (no RUN1_ID)"
  skip "reconcile: fingerprint parity (no RUN1_ID)"
fi

EMPTY_RUNS="$(mktemp -d)"
result=$(printf '{}' | RUNS_DIR="$EMPTY_RUNS" bash "$RECONCILE" 2>/dev/null)
[ -z "$result" ] && pass "reconcile: no breadcrumb -> silent no-op" \
  || fail "reconcile: no breadcrumb -> silent no-op"
rm -rf "$EMPTY_RUNS"

# ---------------------------------------------------------------------------
# SUITE 3 -- track-guard.sh (file edits)
# ---------------------------------------------------------------------------
section "track-guard.sh -- file ownership"

assert_allow "guard: path within allowed prefix -> allow" \
  "$GUARD" \
  "{\"tool_name\":\"create_file\",\"tool_input\":{\"filePath\":\"${ABS}backend-go/postgres.go\"}}" \
  "TRACK_ALLOWED_PREFIXES=backend-go/:frontend/"

assert_deny "guard: path outside allowed prefix -> deny" \
  "$GUARD" \
  "{\"tool_name\":\"create_file\",\"tool_input\":{\"filePath\":\"${ABS}backend-python/main.py\"}}" \
  "TRACK_ALLOWED_PREFIXES=backend-go/:frontend/"

assert_deny "guard: frozen entrypoint -> deny" \
  "$GUARD" \
  "{\"tool_name\":\"replace_string_in_file\",\"tool_input\":{\"filePath\":\"${ABS}backend-go/cmd/api/main.go\"}}" \
  "TRACK_ALLOWED_PREFIXES=backend-go/" \
  "TRACK_FROZEN_PATHS=backend-go/cmd/api/main.go"

TMP_GEN="$(mktemp "${REPO_ROOT}/sbd_tgen_XXXXXX.go")"
printf '// GENERATED \xe2\x80\x94 DO NOT EDIT\n// auto-generated\npackage main\n' > "$TMP_GEN"
result=$(printf '%s' \
  "{\"tool_name\":\"replace_string_in_file\",\"tool_input\":{\"filePath\":\"$TMP_GEN\"}}" \
  | TRACK_ALLOWED_PREFIXES="sbd_tgen_" bash "$GUARD" 2>&1) || true
rm -f "$TMP_GEN"
printf '%s' "$result" | grep -q '"deny"' \
  && pass "guard: GENERATED banner -> deny" || fail "guard: GENERATED banner -> deny"

REAL_COM=".github/instructions/go.instructions.md"
if git log --oneline -1 -- "$REAL_COM" 2>/dev/null | grep -q .; then
  assert_deny "guard: committed file under immutable prefix -> deny" \
    "$GUARD" \
    "{\"tool_name\":\"replace_string_in_file\",\"tool_input\":{\"filePath\":\"${ABS}${REAL_COM}\"}}" \
    "TRACK_ALLOWED_PREFIXES=.github/" \
    "TRACK_IMMUTABLE_PREFIXES=.github/instructions/"
else skip "guard: immutable prefix (file not committed)"; fi

assert_deny "guard: multi_replace with one out-of-scope path -> deny" \
  "$GUARD" \
  "{\"tool_name\":\"multi_replace_string_in_file\",\"tool_input\":{\"replacements\":[{\"filePath\":\"${ABS}backend-go/kernel/auth.go\"},{\"filePath\":\"${ABS}backend-python/main.py\"}]}}" \
  "TRACK_ALLOWED_PREFIXES=backend-go/"

assert_deny "guard: unset TRACK_ALLOWED_PREFIXES -> fail-closed deny" \
  "$GUARD" \
  "{\"tool_name\":\"create_file\",\"tool_input\":{\"filePath\":\"${ABS}anything/test.py\"}}"

# ---------------------------------------------------------------------------
# SUITE 4 -- track-guard.sh (terminal lockout)
# ---------------------------------------------------------------------------
section "track-guard.sh -- terminal lockout"

# Test commands are injected at build time; see note at top of script.
T_PUSH_CMD="git push origin branch"
T_FPUSH_CMD="git push --force origin branch"
T_PRMERGE_CMD="gh pr merge 42 --merge"
T_RESETHARD_CMD="git reset --hard HEAD~1"
T_FFPUSH_CMD="git push origin mybranch"
T_DROP_CMD='DROP TABLE users'
T_FLUSH_CMD="redis-cli FLUSHALL"
T_RMRF_CMD="rm -rf /home/user/data"

mk_term() { printf '{"tool_name":"run_in_terminal","tool_input":{"command":"%s"}}' "$1"; }

assert_deny "guard: worker push blocked -> deny" \
  "$GUARD" "$(mk_term "$T_PUSH_CMD")" "TRACK_ALLOWED_PREFIXES=backend-go/"

assert_deny "guard: force-flag push blocked even with FF_PUSH -> deny" \
  "$GUARD" "$(mk_term "$T_FPUSH_CMD")" \
  "TRACK_ALLOWED_PREFIXES=backend-go/" "TRACK_ALLOW_FF_PUSH=1"

assert_deny "guard: pr-merge command blocked -> deny" \
  "$GUARD" "$(mk_term "$T_PRMERGE_CMD")" "TRACK_ALLOWED_PREFIXES=backend-go/"

assert_deny "guard: reset-hard command blocked -> deny" \
  "$GUARD" "$(mk_term "$T_RESETHARD_CMD")" "TRACK_ALLOWED_PREFIXES=backend-go/"

assert_allow "guard: ff-push with TRACK_ALLOW_FF_PUSH=1 -> allow" \
  "$GUARD" "$(mk_term "$T_FFPUSH_CMD")" \
  "TRACK_ALLOWED_PREFIXES=backend-go/" "TRACK_ALLOW_FF_PUSH=1"

assert_deny "guard: DROP TABLE with TRACK_GUARD_DESTRUCTIVE -> deny" \
  "$GUARD" "$(mk_term "$T_DROP_CMD")" "TRACK_GUARD_DESTRUCTIVE=1"

assert_deny "guard: FLUSHALL with TRACK_GUARD_DESTRUCTIVE -> deny" \
  "$GUARD" "$(mk_term "$T_FLUSH_CMD")" "TRACK_GUARD_DESTRUCTIVE=1"

assert_deny "guard: rm-rf absolute path with TRACK_GUARD_DESTRUCTIVE -> deny" \
  "$GUARD" "$(mk_term "$T_RMRF_CMD")" "TRACK_GUARD_DESTRUCTIVE=1"

# Benign commands MUST pass — guards against an over-broad deny regex regression.
assert_allow "guard: benign 'go test' terminal command -> allow" \
  "$GUARD" "$(mk_term "go test ./...")" "TRACK_ALLOWED_PREFIXES=backend-go/"

assert_allow "guard: benign 'git status' terminal command -> allow" \
  "$GUARD" "$(mk_term "git status")" "TRACK_ALLOWED_PREFIXES=backend-go/"

# A tool that is neither a file-edit nor a terminal call falls through untouched.
assert_allow "guard: unrelated tool (read_file) -> allow (no interception)" \
  "$GUARD" '{"tool_name":"read_file","tool_input":{"filePath":"anything.go"}}'

# ---------------------------------------------------------------------------
# SUITE 5 -- track-evidence.sh (producer) + producer->gate contract
# ---------------------------------------------------------------------------
# The CAPTURE half of the evidence gate. Records here are PRODUCED by
# track-evidence.sh (never hand-written), then fed straight into the real gate so
# the producer->consumer contract (field shape + fingerprint parity) is exercised
# end-to-end. If the producer drifts from the gate, these fail — unit-only tests
# that hand-write the record would not.
section "track-evidence.sh (producer)"

PROD_RUNS="$(mktemp -d)"
PROD_RID="prod-$(date +%s)"

# no-op: RUN_ID unset -> nothing recorded
printf '{"tool_name":"run_in_terminal","tool_input":{"command":"go test ./..."}}' \
  | RUNS_DIR="$PROD_RUNS" TRACK_TEST_CMD_PATTERN="go test" bash "$EVIDENCE" >/dev/null 2>&1 || true
[ -z "$(ls -A "$PROD_RUNS" 2>/dev/null)" ] \
  && pass "evidence(producer): RUN_ID unset -> no record written" \
  || fail "evidence(producer): RUN_ID unset -> no record written"

# no-op: no matcher declared -> nothing recorded
printf '{"tool_name":"run_in_terminal","tool_input":{"command":"go test ./..."}}' \
  | RUN_ID="$PROD_RID" RUNS_DIR="$PROD_RUNS" bash "$EVIDENCE" >/dev/null 2>&1 || true
[ ! -f "$PROD_RUNS/$PROD_RID.json" ] \
  && pass "evidence(producer): no matcher set -> no record written" \
  || fail "evidence(producer): no matcher set -> no record written"

# no-op: non-terminal tool is ignored
printf '{"tool_name":"create_file","tool_input":{"filePath":"x.go"}}' \
  | RUN_ID="$PROD_RID" RUNS_DIR="$PROD_RUNS" TRACK_TEST_CMD_PATTERN="go test" \
    bash "$EVIDENCE" >/dev/null 2>&1 || true
[ ! -f "$PROD_RUNS/$PROD_RID.json" ] \
  && pass "evidence(producer): non-terminal tool -> no record" \
  || fail "evidence(producer): non-terminal tool -> no record"

# TRACK_TEST_CMD_PATTERN match -> recorded with default kind "test"
printf '{"tool_name":"run_in_terminal","tool_input":{"command":"go test ./..."},"tool_response":"ok  0.5s"}' \
  | RUN_ID="$PROD_RID" RUNS_DIR="$PROD_RUNS" TRACK_TEST_CMD_PATTERN="go test" \
    bash "$EVIDENCE" >/dev/null 2>&1 || true
kind_seen=$(jq -r '.evidence[-1].kind // empty' "$PROD_RUNS/$PROD_RID.json" 2>/dev/null)
[ "$kind_seen" = "test" ] \
  && pass "evidence(producer): TEST_CMD_PATTERN match -> kind=test recorded" \
  || fail "evidence(producer): TEST_CMD_PATTERN match -> kind=test (got: $kind_seen)"

# TRACK_EVIDENCE_KINDS label:pattern derivation (first match wins)
PROD_RID2="prod2-$(date +%s)"
printf '{"tool_name":"run_in_terminal","tool_input":{"command":"go test -race ./..."},"tool_response":"ok"}' \
  | RUN_ID="$PROD_RID2" RUNS_DIR="$PROD_RUNS" \
    TRACK_EVIDENCE_KINDS="go-test:go test -race;py:uv run pytest" \
    bash "$EVIDENCE" >/dev/null 2>&1 || true
kind2=$(jq -r '.evidence[-1].kind // empty' "$PROD_RUNS/$PROD_RID2.json" 2>/dev/null)
[ "$kind2" = "go-test" ] \
  && pass "evidence(producer): EVIDENCE_KINDS label derived (go-test)" \
  || fail "evidence(producer): EVIDENCE_KINDS label derived (got: $kind2)"

# Producer fingerprint MUST equal the current tree fingerprint (== gate's compute)
fp_prod=$(jq -r '.evidence[-1].fingerprint // empty' "$PROD_RUNS/$PROD_RID2.json" 2>/dev/null)
fp_now=$(current_fingerprint)
[ -n "$fp_prod" ] && [ "$fp_prod" = "$fp_now" ] \
  && pass "evidence(producer): fingerprint == current tree (producer<->gate parity)" \
  || fail "evidence(producer): fingerprint mismatch (producer=$fp_prod now=$fp_now)"

# END-TO-END: a producer-captured pass at the current FP satisfies the real gate
result=$(printf '{"stop_hook_active":false}' | RUN_ID="$PROD_RID2" RUNS_DIR="$PROD_RUNS" \
         TRACK_REQUIRED_EVIDENCE="go-test" bash "$EVIDENCE_GATE" 2>&1) || true
[ -z "$result" ] \
  && pass "evidence(e2e): producer pass at current FP -> gate allows" \
  || fail "evidence(e2e): producer pass -> gate allows (got: $result)"

# END-TO-END: a second required kind with no producer entry -> gate blocks, names it
result=$(printf '{"stop_hook_active":false}' | RUN_ID="$PROD_RID2" RUNS_DIR="$PROD_RUNS" \
         TRACK_REQUIRED_EVIDENCE="go-test,py" bash "$EVIDENCE_GATE" 2>&1) || true
if printf '%s' "$result" | grep -qiE '"block"|MISSING' && printf '%s' "$result" | grep -q 'py'; then
  pass "evidence(e2e): multi-kind, one kind missing -> gate blocks (names py)"
else fail "evidence(e2e): multi-kind missing -> gate blocks (got: $result)"; fi

rm -rf "$PROD_RUNS"

# ---------------------------------------------------------------------------
# SUITE 6 -- track-evidence-gate.sh
# ---------------------------------------------------------------------------
section "track-evidence-gate.sh"

if [ -n "$RUN1_ID" ]; then
  EMPTY_REC="$(mktemp -d)"
  result=$(printf '{"stop_hook_active":false}' | RUN_ID="$RUN1_ID" RUNS_DIR="$EMPTY_REC" \
           TRACK_REQUIRED_EVIDENCE="go-test" bash "$EVIDENCE_GATE" 2>&1) || true
  rm -rf "$EMPTY_REC"
  printf '%s' "$result" | grep -q '"block"' \
    && pass "evidence-gate: missing run record -> block" \
    || fail "evidence-gate: missing run record -> block"

  result=$(printf '{"stop_hook_active":true}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" \
           TRACK_REQUIRED_EVIDENCE="go-test" bash "$EVIDENCE_GATE" 2>&1) || true
  [ -z "$result" ] && pass "evidence-gate: stop_hook_active -> no-op" \
    || fail "evidence-gate: stop_hook_active -> no-op"

  result=$(printf '{"stop_hook_active":false}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" \
           bash "$EVIDENCE_GATE" 2>&1) || true
  [ -z "$result" ] && pass "evidence-gate: no required evidence -> no-op" \
    || fail "evidence-gate: no required evidence -> no-op"

  FP=$(current_fingerprint)
  jq -nc --arg fp "$FP" \
    '{"evidence":[{"kind":"go-test","cmd":"go test","response":"ok","fingerprint":$fp}]}' \
    > "$TMPDIR_RUNS/$RUN1_ID.json"
  result=$(printf '{"stop_hook_active":false}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" \
           TRACK_REQUIRED_EVIDENCE="go-test" bash "$EVIDENCE_GATE" 2>&1) || true
  [ -z "$result" ] && pass "evidence-gate: fresh evidence at current FP -> allow" \
    || fail "evidence-gate: fresh evidence at current FP -> allow (got: $result)"

  jq -nc '{"evidence":[{"kind":"go-test","cmd":"go test","response":"ok","fingerprint":"0000000000000000000000000000000000000001"}]}' \
    > "$TMPDIR_RUNS/$RUN1_ID.json"
  result=$(printf '{"stop_hook_active":false}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" \
           TRACK_REQUIRED_EVIDENCE="go-test" bash "$EVIDENCE_GATE" 2>&1) || true
  printf '%s' "$result" | grep -qiE '"block"|STALE' \
    && pass "evidence-gate: stale FP -> block" || fail "evidence-gate: stale FP -> block"

  FP=$(current_fingerprint)
  jq -nc --arg fp "$FP" \
    '{"evidence":[{"kind":"go-test","cmd":"go test","response":"--- FAIL: TestX\nFAIL\texit code 1","fingerprint":$fp}]}' \
    > "$TMPDIR_RUNS/$RUN1_ID.json"
  result=$(printf '{"stop_hook_active":false}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" \
           TRACK_REQUIRED_EVIDENCE="go-test" bash "$EVIDENCE_GATE" 2>&1) || true
  printf '%s' "$result" | grep -qiE '"block"|FAILING' \
    && pass "evidence-gate: FAIL marker -> block" || fail "evidence-gate: FAIL marker -> block"

  # Multi-kind: one kind fresh+passing, a second REQUIRED kind absent -> block naming it.
  FP=$(current_fingerprint)
  jq -nc --arg fp "$FP" \
    '{"evidence":[{"kind":"go-test","cmd":"go test","response":"ok","fingerprint":$fp}]}' \
    > "$TMPDIR_RUNS/$RUN1_ID.json"
  result=$(printf '{"stop_hook_active":false}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" \
           TRACK_REQUIRED_EVIDENCE="go-test,py" bash "$EVIDENCE_GATE" 2>&1) || true
  if printf '%s' "$result" | grep -qiE '"block"|MISSING' && printf '%s' "$result" | grep -q 'py'; then
    pass "evidence-gate: multi-kind, second kind missing -> block names it"
  else fail "evidence-gate: multi-kind missing -> block (got: $result)"; fi
else
  for i in 1 2 3 4 5 6 7; do skip "evidence-gate: skipped (no RUN1_ID)"; done
fi

# ---------------------------------------------------------------------------
# SUITE 7 -- track-sentinel.sh
# ---------------------------------------------------------------------------
section "track-sentinel.sh"

result=$(printf '{"stop_hook_active":true}' | TRACK_SENTINEL=1 bash "$SENTINEL" 2>&1) || true
[ -z "$result" ] && pass "sentinel: stop_hook_active -> no-op" \
  || fail "sentinel: stop_hook_active -> no-op"

result=$(printf '{"stop_hook_active":false}' | bash "$SENTINEL" 2>&1) || true
[ -z "$result" ] && pass "sentinel: TRACK_SENTINEL unset -> no-op" \
  || fail "sentinel: TRACK_SENTINEL unset -> no-op"

TMP_SECRET="sbd_tst_secret_$$.py"
# Deliberately split so push-protection scanners never see a valid key pattern.
# The sentinel checks for 'sk_' + 'live_' as separate regex components.
printf 'API_KEY = "sk_''live_''TEST_SENTINEL_FIXTURE_NOT_A_SECRET"\n' > "$TMP_SECRET"
git add "$TMP_SECRET"
SCRATCH_FILES+=("$TMP_SECRET")
result=$(printf '{"stop_hook_active":false}' | TRACK_SENTINEL=1 bash "$SENTINEL" 2>&1) || true
git rm --cached "$TMP_SECRET" --quiet 2>/dev/null || true; rm -f "$TMP_SECRET"
printf '%s' "$result" | grep -q '"block"' \
  && pass "sentinel: staged secret -> block" || fail "sentinel: staged secret -> block"

TMP_DEBUG="sbd_tst_debug_$$.ts"
printf 'export function foo() {\n  console.log("debug:", x);\n}\n' > "$TMP_DEBUG"
git add "$TMP_DEBUG"
SCRATCH_FILES+=("$TMP_DEBUG")
result=$(printf '{"stop_hook_active":false}' | TRACK_SENTINEL=1 bash "$SENTINEL" 2>&1) || true
git rm --cached "$TMP_DEBUG" --quiet 2>/dev/null || true; rm -f "$TMP_DEBUG"
printf '%s' "$result" | grep -q '"block"' \
  && pass "sentinel: console.log leftover -> block" || fail "sentinel: console.log leftover -> block"

# ---------------------------------------------------------------------------
# SUITE 8 -- track-meter.sh
# ---------------------------------------------------------------------------
section "track-meter.sh"

result=$(jq -nc '{"tool_name":"create_file","tool_response":"ok"}' | \
         RUN_ID="${RUN1_ID:-test}" RUNS_DIR="$TMPDIR_RUNS" TRACK_MAX_TOOL_CALLS=100 \
         bash "$METER" 2>&1) || true
printf '%s' "$result" | grep -qF '"continue":false' \
  && fail "meter: under ceiling -> allow" || pass "meter: under ceiling -> allow"

result=$(jq -nc '{"tool_name":"create_file","tool_response":"ok"}' | \
         RUN_ID="${RUN1_ID:-test}" RUNS_DIR="$TMPDIR_RUNS" TRACK_MAX_TOOL_CALLS=0 \
         bash "$METER" 2>&1) || true
printf '%s' "$result" | grep -qF '"continue":false' \
  && pass "meter: ceiling=0 -> block" || fail "meter: ceiling=0 -> block"

result=$(jq -nc '{"tool_name":"create_file","tool_response":"ok"}' | \
         RUN_ID="${RUN1_ID:-test}" RUNS_DIR="$TMPDIR_RUNS" bash "$METER" 2>&1) || true
printf '%s' "$result" | grep -qF '"continue":false' \
  && fail "meter: unset ceiling -> no-op" || pass "meter: unset ceiling -> no-op"

# Accumulation + terminal state: three calls against a ceiling of 2 — the count
# must persist across calls, trip on the call that pushes it past the ceiling, and
# stamp status=no-progress for the orchestrator summary.
ACC_RUNS="$(mktemp -d)"; ACC_RID="meter-acc"
out=""
for _ in 1 2 3; do
  out=$(jq -nc '{"tool_name":"create_file","tool_response":"ok"}' | \
        RUN_ID="$ACC_RID" RUNS_DIR="$ACC_RUNS" TRACK_MAX_TOOL_CALLS=2 bash "$METER" 2>&1) || true
done
printf '%s' "$out" | grep -qF '"continue":false' \
  && pass "meter: count accumulates across calls, trips past ceiling" \
  || fail "meter: count accumulates across calls, trips past ceiling (got: $out)"
status_seen=$(jq -r '.status // empty' "$ACC_RUNS/$ACC_RID.json" 2>/dev/null)
[ "$status_seen" = "no-progress" ] \
  && pass "meter: ceiling trip records status=no-progress" \
  || fail "meter: ceiling trip records status=no-progress (got: $status_seen)"
rm -rf "$ACC_RUNS"

# Heartbeat: every meter write stamps started_ts (once) + last_ts (every call) so the
# orchestrator can derive idle-staleness and run wall-clock.
HB_RUNS="$(mktemp -d)"; HB_RID="meter-hb"
jq -nc '{"tool_name":"create_file","tool_response":"ok"}' | \
  RUN_ID="$HB_RID" RUNS_DIR="$HB_RUNS" TRACK_MAX_TOOL_CALLS=100 bash "$METER" >/dev/null 2>&1 || true
if jq -e '(.started_ts | type == "string" and . != "") and (.last_ts | type == "string" and . != "")' \
     "$HB_RUNS/$HB_RID.json" >/dev/null 2>&1; then
  pass "meter: stamps started_ts + last_ts heartbeat"
else
  fail "meter: stamps started_ts + last_ts heartbeat"
fi
rm -rf "$HB_RUNS"

# ---------------------------------------------------------------------------
# SUITE 9 -- track-trace.sh
# ---------------------------------------------------------------------------
section "track-trace.sh"

jq -nc '{"run_id":"'"${RUN1_ID:-test}"'","v":1,"trace":[],"evidence":[],"tool_calls":0}' \
  > "$TMPDIR_RUNS/${RUN1_ID:-test}.json"
jq -nc '{"hook_event_name":"SubagentStart","agent_id":"a001","agent_type":"impl"}' | \
  RUN_ID="${RUN1_ID:-test}" RUNS_DIR="$TMPDIR_RUNS" bash "$TRACE" >/dev/null 2>&1 || true
trace_len=$(jq '.trace | length' "$TMPDIR_RUNS/${RUN1_ID:-test}.json" 2>/dev/null || echo 0)
[ "$trace_len" -ge 1 ] && pass "trace: SubagentStart -> appended to run record" \
  || fail "trace: SubagentStart -> appended to run record"

# enriched: agent_description (SubagentStart-only "why") is captured as reason
jq -nc '{"hook_event_name":"SubagentStart","agent_id":"a002","agent_type":"Explore","agent_description":"map the auth flow"}' | \
  RUN_ID="${RUN1_ID:-test}" RUNS_DIR="$TMPDIR_RUNS" bash "$TRACE" >/dev/null 2>&1 || true
if jq -e '[.trace[] | select(.reason == "map the auth flow")] | length == 1' \
     "$TMPDIR_RUNS/${RUN1_ID:-test}.json" >/dev/null 2>&1; then
  pass "trace: agent_description captured as reason"
else
  fail "trace: agent_description captured as reason"
fi

# camelCase surface: agentName + stop_reason are read too
jq -nc '{"hook_event_name":"SubagentStop","agentName":"Explore","stop_reason":"end_turn"}' | \
  RUN_ID="${RUN1_ID:-test}" RUNS_DIR="$TMPDIR_RUNS" bash "$TRACE" >/dev/null 2>&1 || true
if jq -e '[.trace[] | select(.agent_type == "Explore" and .stop_reason == "end_turn")] | length == 1' \
     "$TMPDIR_RUNS/${RUN1_ID:-test}.json" >/dev/null 2>&1; then
  pass "trace: camelCase agentName + stop_reason captured"
else
  fail "trace: camelCase agentName + stop_reason captured"
fi

result=$(jq -nc '{"hook_event_name":"SubagentStart"}' | bash "$TRACE" 2>&1) || true
[ -z "$result" ] && pass "trace: no RUN_ID -> no-op" || fail "trace: no RUN_ID -> no-op"

# ---------------------------------------------------------------------------
# SUITE 9b -- track-note.sh (SELF-REPORTED skills[] + iterations)
# ---------------------------------------------------------------------------
section "track-note.sh"
NOTE_RUNS="$(mktemp -d)"; NOTE_RID="note-run"

# skill: appends an ordered, provenance-tagged entry to skills[]
RUN_ID="$NOTE_RID" RUNS_DIR="$NOTE_RUNS" bash "$NOTE" skill test-driven-development red >/dev/null 2>&1 || true
RUN_ID="$NOTE_RID" RUNS_DIR="$NOTE_RUNS" bash "$NOTE" skill requesting-code-review review >/dev/null 2>&1 || true
if jq -e '(.skills | length == 2) and (.skills[0].skill == "test-driven-development") and (.skills[0].step == "red") and (.skills[0].self_reported == true)' \
     "$NOTE_RUNS/$NOTE_RID.json" >/dev/null 2>&1; then
  pass "note: skill appends ordered self_reported skills[] entry"
else
  fail "note: skill appends ordered self_reported skills[] entry"
fi

# loop: increments iterations, sets the provenance flag, logs the phase
RUN_ID="$NOTE_RID" RUNS_DIR="$NOTE_RUNS" bash "$NOTE" loop cycle-1 >/dev/null 2>&1 || true
RUN_ID="$NOTE_RID" RUNS_DIR="$NOTE_RUNS" bash "$NOTE" loop cycle-2 >/dev/null 2>&1 || true
if jq -e '.iterations == 2 and .iterations_self_reported == true and (.iteration_log | length == 2)' \
     "$NOTE_RUNS/$NOTE_RID.json" >/dev/null 2>&1; then
  pass "note: loop increments iterations + tags provenance + logs phase"
else
  fail "note: loop increments iterations + tags provenance + logs phase"
fi

# note writes preserve the canonical skeleton (co-exist with hook fields)
if jq -e 'has("run_id") and .v == 1 and (.trace | type == "array") and (.evidence | type == "array") and (.tool_calls | type == "number")' \
     "$NOTE_RUNS/$NOTE_RID.json" >/dev/null 2>&1; then
  pass "note: preserves canonical skeleton (run_id/v/trace/evidence/tool_calls)"
else
  fail "note: preserves canonical skeleton (run_id/v/trace/evidence/tool_calls)"
fi

# opt-in: no RUN_ID -> silent no-op, writes nothing
before=$(ls "$NOTE_RUNS" | wc -l)
RUNS_DIR="$NOTE_RUNS" bash "$NOTE" skill should-not-write >/dev/null 2>&1 || true
after=$(ls "$NOTE_RUNS" | wc -l)
[ "$before" -eq "$after" ] \
  && pass "note: no RUN_ID -> silent no-op (writes nothing)" \
  || fail "note: no RUN_ID -> silent no-op (writes nothing)"

# bad subcommand -> non-zero, no write
RUN_ID="$NOTE_RID" RUNS_DIR="$NOTE_RUNS" bash "$NOTE" bogus >/dev/null 2>&1 \
  && fail "note: unknown subcommand -> non-zero exit" \
  || pass "note: unknown subcommand -> non-zero exit"
rm -rf "$NOTE_RUNS"

# ---------------------------------------------------------------------------
# SUITE 9c -- track-tokens.sh (opt-in transcript token estimate)
# ---------------------------------------------------------------------------
section "track-tokens.sh"
TOK_RUNS="$(mktemp -d)"; TOK_RID="tok-run"
jq -nc '{"run_id":"'"$TOK_RID"'","v":1,"trace":[],"evidence":[],"tool_calls":0}' \
  > "$TOK_RUNS/$TOK_RID.json"

# Build a minimal transcript fixture with all three text-bearing record types.
TOK_TX="$(mktemp)"
printf '%s\n' \
  '{"type":"user.message","data":{"content":"implement the auth handler"}}' \
  '{"type":"assistant.message","data":{"content":"I will write the handler","reasoningText":"checking the spec","toolRequests":[{"name":"read_file","args":{"filePath":"auth.go"}}]}}' \
  '{"type":"tool.execution_start","data":{"toolName":"read_file","toolCallId":"t1","arguments":{"filePath":"auth.go"}}}' \
  '{"type":"tool.execution_complete","data":{"toolCallId":"t1","success":true}}' \
  > "$TOK_TX"

# With TRACK_TOKEN_ESTIMATE=1 it should write token_estimate to the record.
printf '{"hook_event_name":"Stop","transcript_path":"%s"}' "$TOK_TX" | \
  TRACK_TOKEN_ESTIMATE=1 RUN_ID="$TOK_RID" RUNS_DIR="$TOK_RUNS" bash "$TOKENS" >/dev/null 2>&1 || true
if jq -e '.token_estimate > 0 and (.token_estimate_method | test("chars")) and (.token_estimate_chars > 0)' \
     "$TOK_RUNS/$TOK_RID.json" >/dev/null 2>&1; then
  pass "tokens: writes token_estimate + method with TRACK_TOKEN_ESTIMATE=1"
else
  fail "tokens: writes token_estimate + method with TRACK_TOKEN_ESTIMATE=1"
fi

# Overwrite behaviour: a second Stop call must OVERWRITE, not add, the estimate.
est1="$(jq '.token_estimate' "$TOK_RUNS/$TOK_RID.json")"
printf '{"hook_event_name":"Stop","transcript_path":"%s"}' "$TOK_TX" | \
  TRACK_TOKEN_ESTIMATE=1 RUN_ID="$TOK_RID" RUNS_DIR="$TOK_RUNS" bash "$TOKENS" >/dev/null 2>&1 || true
est2="$(jq '.token_estimate' "$TOK_RUNS/$TOK_RID.json")"
[ "$est1" -eq "$est2" ] \
  && pass "tokens: repeated Stop overwrites estimate (not additive)" \
  || fail "tokens: repeated Stop overwrites estimate (not additive)"

# No-op without TRACK_TOKEN_ESTIMATE (the field must not appear).
jq -nc '{"run_id":"tok-off","v":1,"trace":[],"evidence":[],"tool_calls":0}' \
  > "$TOK_RUNS/tok-off.json"
printf '{"hook_event_name":"Stop","transcript_path":"%s"}' "$TOK_TX" | \
  TRACK_TOKEN_ESTIMATE="" RUN_ID="tok-off" RUNS_DIR="$TOK_RUNS" bash "$TOKENS" >/dev/null 2>&1 || true
if jq -e '.token_estimate == null' "$TOK_RUNS/tok-off.json" >/dev/null 2>&1; then
  pass "tokens: no-op without TRACK_TOKEN_ESTIMATE"
else
  fail "tokens: no-op without TRACK_TOKEN_ESTIMATE"
fi

rm -rf "$TOK_RUNS" "$TOK_TX"

# ---------------------------------------------------------------------------
# SUITE 10 -- track-notify.sh
# ---------------------------------------------------------------------------
# Best-effort, fire-and-forget: with no webhook configured it must stay a silent
# no-op and NEVER emit a blocking decision (it runs on Stop after the gate).
section "track-notify.sh"

result=$(printf '{}' | RUN_ID="${RUN1_ID:-test}" RUNS_DIR="$TMPDIR_RUNS" bash "$NOTIFY" 2>&1) || true
[ -z "$result" ] \
  && pass "notify: no webhook -> silent no-op (never blocks)" \
  || fail "notify: no webhook -> silent no-op (got: $result)"

# ---------------------------------------------------------------------------
# SUITE 10b -- install-hooks.sh (idempotent, consent-gated, drift-aware, stack-aware)
# ---------------------------------------------------------------------------
section "install-hooks.sh"

# Build an isolated throwaway repo with go + python + spec signals; run the installer there.
IH_REPO="$(mktemp -d)"
(
  cd "$IH_REPO"
  git init -q
  mkdir -p backend-go backend-python specs/x migrations
  : > backend-go/go.mod; : > backend-python/pyproject.toml; : > specs/x/plan.md
)

# --check on a bare repo -> drift (exit 3), writes nothing
if ( cd "$IH_REPO" && bash "$INSTALL_HOOKS" --check >/dev/null 2>&1 ); then
  fail "install: --check on unwired repo -> non-zero (drift)"
else
  pass "install: --check on unwired repo -> non-zero (drift)"
fi

# dry-run writes nothing
before_ct=$(find "$IH_REPO/.github/hooks" -type f 2>/dev/null | wc -l | tr -d ' ' || echo 0)
( cd "$IH_REPO" && bash "$INSTALL_HOOKS" >/dev/null 2>&1 ) || true
after_ct=$(find "$IH_REPO/.github/hooks" -type f 2>/dev/null | wc -l | tr -d ' ' || echo 0)
[ "$before_ct" = "$after_ct" ] \
  && pass "install: dry-run writes nothing" \
  || fail "install: dry-run writes nothing (before=$before_ct after=$after_ct)"

# --apply: syncs bundle, gitignores runs/, seeds base preset
( cd "$IH_REPO" && bash "$INSTALL_HOOKS" --apply >/dev/null 2>&1 ) || true
if [ -f "$IH_REPO/.github/hooks/track-preflight.sh" ] && [ -f "$IH_REPO/.github/hooks/track-hooks.json" ]; then
  pass "install: --apply syncs bundle into .github/hooks/"
else
  fail "install: --apply syncs bundle into .github/hooks/"
fi
( cd "$IH_REPO" && git check-ignore runs/ >/dev/null 2>&1 ) \
  && pass "install: --apply gitignores runs/" \
  || fail "install: --apply gitignores runs/"
[ -f "$IH_REPO/.github/hooks/track-env.base.sh" ] \
  && pass "install: --apply seeds track-env.base.sh" \
  || fail "install: --apply seeds track-env.base.sh"

# stack-aware: detected go + py signals populate the evidence catalog + toolchain hint
if grep -q 'go-test:go test' "$IH_REPO/.github/hooks/track-env.base.sh" 2>/dev/null \
   && grep -q 'py:uv run pytest' "$IH_REPO/.github/hooks/track-env.base.sh" 2>/dev/null; then
  pass "install: base preset is stack-aware (go-test + py catalog from detected signals)"
else
  fail "install: base preset is stack-aware (go-test + py catalog from detected signals)"
fi

# TASK-DERIVED scope stays EMPTY so an unedited copy fails loud (guard denies all edits)
if grep -qE 'TRACK_ALLOWED_PREFIXES="\$\{TRACK_ALLOWED_PREFIXES:-\}"' "$IH_REPO/.github/hooks/track-env.base.sh" 2>/dev/null; then
  pass "install: TASK-DERIVED writable scope left empty (fail-loud)"
else
  fail "install: TASK-DERIVED writable scope left empty (fail-loud)"
fi

# generated base preset sources cleanly under the hooks' shell flags
if ( cd "$IH_REPO" && bash -c 'set -eufo pipefail; source .github/hooks/track-env.base.sh' >/dev/null 2>&1 ); then
  pass "install: generated track-env.base.sh sources cleanly (set -eufo pipefail)"
else
  fail "install: generated track-env.base.sh sources cleanly (set -eufo pipefail)"
fi

# after --apply, --check is clean (exit 0)
if ( cd "$IH_REPO" && bash "$INSTALL_HOOKS" --check >/dev/null 2>&1 ); then
  pass "install: --check after --apply -> clean (exit 0)"
else
  fail "install: --check after --apply -> clean (exit 0)"
fi

# idempotent + never-clobber: edit the base preset, re-apply, edit must survive
printf '\n# USER EDIT MARKER\n' >> "$IH_REPO/.github/hooks/track-env.base.sh"
( cd "$IH_REPO" && bash "$INSTALL_HOOKS" --apply >/dev/null 2>&1 ) || true
if grep -q 'USER EDIT MARKER' "$IH_REPO/.github/hooks/track-env.base.sh" 2>/dev/null; then
  pass "install: re-apply never clobbers an existing track-env.base.sh"
else
  fail "install: re-apply never clobbers an existing track-env.base.sh"
fi

# drift is repaired: stale an installed script, --check must flag it, --apply must fix it
printf '# STALE\n' > "$IH_REPO/.github/hooks/track-preflight.sh"
if ( cd "$IH_REPO" && bash "$INSTALL_HOOKS" --check >/dev/null 2>&1 ); then
  fail "install: --check detects a drifted (stale) installed script"
else
  pass "install: --check detects a drifted (stale) installed script"
fi
( cd "$IH_REPO" && bash "$INSTALL_HOOKS" --apply >/dev/null 2>&1 ) || true
if cmp -s "$SCRIPTS_DIR/track-preflight.sh" "$IH_REPO/.github/hooks/track-preflight.sh"; then
  pass "install: --apply re-syncs a drifted script back to source"
else
  fail "install: --apply re-syncs a drifted script back to source"
fi
rm -rf "$IH_REPO"

# ---------------------------------------------------------------------------
# SUITE 10b -- track-report.sh (deterministic PR-body Auto block)
# ---------------------------------------------------------------------------
section "track-report.sh"
REPORT="$SCRIPTS_DIR/track-report.sh"
[ -x "$REPORT" ] || chmod +x "$REPORT"

# Build a throwaway git repo + populated run record so the report has real diff + record.
RPT_REPO="$(mktemp -d)"
(
  cd "$RPT_REPO" && git init -q && git config user.email t@t && git config user.name t
  echo hi > a.go && git add a.go && git commit -q -m init
  echo more >> a.go && echo new > b.py && git add -A && git commit -q -m work
  mkdir -p runs
  RID="2026-01-02T03-04_setup"
  printf '{"run_id":"%s","branch":"feat-x","tasks":"T1-T3","created_utc":"2026-01-02T03:00:00Z","completed_utc":"2026-01-02T03:48:00Z","duration_secs":2880}\n' "$RID" > "runs/$RID.dispatch"
  cat > "runs/$RID.json" <<JSON
{"run_id":"$RID","v":1,"tool_calls":42,"started_ts":"2026-01-02T03:00:05Z","last_ts":"2026-01-02T03:47:55Z","iterations":3,
 "trace":[{"t":"2026-01-02T03:05Z","kind":"subagent","event":"SubagentStart","agent_id":"s1","agent_type":"Explore"}],
 "skills":[{"t":"2026-01-02T03:01Z","skill":"single-branch-development","step":"scaffold","self_reported":true}],
 "evidence":[{"kind":"go-test","cmd":"go test ./...","response":"ok pkg","fingerprint":"abc123def456ghi"},{"kind":"py","cmd":"uv run pytest","response":"1 failed\nAssertionError","fingerprint":"abc123def456ghi"}]}
JSON
)
RID="2026-01-02T03-04_setup"
RPT_MD="$(cd "$RPT_REPO" && TRACK_BASE_REF=HEAD~1 RUNS_DIR=runs bash "$REPORT" "$RID" 2>&1 || true)"

# 10b.1 — renders without a printf/jq error
printf '%s' "$RPT_MD" | grep -qiE 'invalid option|usage: printf|jq: error' \
  && fail "report: renders clean (no printf/jq errors)" \
  || pass "report: renders clean (no printf/jq errors)"

# 10b.2 — changed files come from the DIFF (a.go modified, b.py added)
if printf '%s' "$RPT_MD" | grep -q 'a.go' && printf '%s' "$RPT_MD" | grep -q 'b.py'; then
  pass "report: files-changed table rendered from git diff"
else
  fail "report: files-changed table rendered from git diff"
fi

# 10b.3 — evidence pass/fail derived from recorded response text
if printf '%s' "$RPT_MD" | grep -qE 'go-test.*pass' && printf '%s' "$RPT_MD" | grep -qE 'py.*FAIL'; then
  pass "report: evidence pass/fail derived from record response"
else
  fail "report: evidence pass/fail derived from record response"
fi

# 10b.4 — mechanical tool_calls surfaced from the record
printf '%s' "$RPT_MD" | grep -q 'Tool calls:.*42' \
  && pass "report: tool_calls surfaced from record" \
  || fail "report: tool_calls surfaced from record"

# 10b.5 — self-reported skills/iterations fenced UNDER a self-reported heading
if printf '%s' "$RPT_MD" | grep -qi 'self-reported' \
   && printf '%s' "$RPT_MD" | grep -q 'Iterations.*3'; then
  pass "report: self-reported trace clearly labelled + separated"
else
  fail "report: self-reported trace clearly labelled + separated"
fi

# 10b.6 — RUN_ID recovered from the newest breadcrumb when none supplied
RPT_REC="$(cd "$RPT_REPO" && TRACK_BASE_REF=HEAD~1 RUNS_DIR=runs bash "$REPORT" 2>&1 || true)"
printf '%s' "$RPT_REC" | grep -q "$RID" \
  && pass "report: recovers RUN_ID from newest breadcrumb" \
  || fail "report: recovers RUN_ID from newest breadcrumb"

# 10b.7 — --json emits valid JSON carrying the same facts
RPT_JSON="$(cd "$RPT_REPO" && TRACK_BASE_REF=HEAD~1 RUNS_DIR=runs bash "$REPORT" --json "$RID" 2>/dev/null || true)"
if printf '%s' "$RPT_JSON" | jq -e '.tool_calls == 42 and (.evidence | length) == 2' >/dev/null 2>&1; then
  pass "report: --json is valid + carries the same facts"
else
  fail "report: --json is valid + carries the same facts"
fi

# 10b.8 — read-only: the record is byte-identical after reporting
if cmp -s "$RPT_REPO/runs/$RID.json" "$RPT_REPO/runs/$RID.json"; then
  RPT_BEFORE="$(cat "$RPT_REPO/runs/$RID.json")"
  (cd "$RPT_REPO" && TRACK_BASE_REF=HEAD~1 RUNS_DIR=runs bash "$REPORT" "$RID" >/dev/null 2>&1 || true)
  [ "$(cat "$RPT_REPO/runs/$RID.json")" = "$RPT_BEFORE" ] \
    && pass "report: read-only (never mutates the run record)" \
    || fail "report: read-only (never mutates the run record)"
fi
rm -rf "$RPT_REPO"

# 10b.9/10 — compliance warnings surface silent omissions (empty evidence / no review)
RPT_W="$(mktemp -d)"
(
  cd "$RPT_W" && git init -q && git config user.email t@t && git config user.name t
  echo x > f.txt && git add f.txt && git commit -q -m init
  mkdir -p runs
  # (a) bare record: no evidence, no code-review activation -> BOTH warnings fire
  printf '{"run_id":"R-bare"}\n' > runs/R-bare.dispatch
  printf '{"run_id":"R-bare","v":1,"tool_calls":1,"evidence":[],"skills":[]}\n' > runs/R-bare.json
  # (b) complete record: evidence + a requesting-code-review activation -> NO warnings
  printf '{"run_id":"R-ok"}\n' > runs/R-ok.dispatch
  cat > runs/R-ok.json <<JSON
{"run_id":"R-ok","v":1,"tool_calls":1,
 "evidence":[{"kind":"go-test","cmd":"go test ./...","response":"ok","fingerprint":"f1"}],
 "skills":[{"t":"t","skill":"requesting-code-review","step":"review","self_reported":true}]}
JSON
)
W_BARE="$(cd "$RPT_W" && TRACK_BASE_REF=HEAD RUNS_DIR=runs bash "$REPORT" R-bare 2>&1 || true)"
W_BARE_J="$(cd "$RPT_W" && RUNS_DIR=runs bash "$REPORT" --json R-bare 2>/dev/null || true)"
W_OK="$(cd "$RPT_W" && TRACK_BASE_REF=HEAD RUNS_DIR=runs bash "$REPORT" R-ok 2>&1 || true)"

# 10b.9 — bare record warns about BOTH missing evidence and missing review
if printf '%s' "$W_BARE" | grep -qi 'Compliance warnings' \
   && printf '%s' "$W_BARE" | grep -qi 'evidence gate ran on an empty pack' \
   && printf '%s' "$W_BARE" | grep -qi 'may have been skipped'; then
  pass "report: flags empty evidence + missing review as compliance warnings"
else
  fail "report: flags empty evidence + missing review as compliance warnings"
fi

# 10b.9b — --json exposes the warnings[] array
if printf '%s' "$W_BARE_J" | jq -e '(.warnings | length) == 2' >/dev/null 2>&1; then
  pass "report: --json exposes warnings[] array"
else
  fail "report: --json exposes warnings[] array"
fi

# 10b.10 — a record WITH review activation + evidence produces NO warnings
if printf '%s' "$W_OK" | grep -qi 'A code-review activation and at least one evidence row' \
   && ! printf '%s' "$W_OK" | grep -qi 'may have been skipped'; then
  pass "report: no compliance warnings when review + evidence are on record"
else
  fail "report: no compliance warnings when review + evidence are on record"
fi
rm -rf "$RPT_W"

# 10b.11/12 — files-changed grouping: many files → area summary + collapsible list;
#             few files → a plain per-file table (no <details>).
RPT_G="$(mktemp -d)"
(
  cd "$RPT_G" && git init -q && git config user.email t@t && git config user.name t
  git commit -q --allow-empty -m base
  # 15 files across 3 areas (> default threshold of 12) → grouped
  for d in alpha beta gamma; do
    mkdir -p "$d"
    for i in 1 2 3 4 5; do echo x > "$d/f$i.txt"; done
  done
  git add -A && git commit -q -m many
)
RPT_MANY="$(cd "$RPT_G" && TRACK_BASE_REF=HEAD~1 RUNS_DIR=runs bash "$REPORT" R-none 2>&1 || true)"

# 10b.11 — area summary table present, with per-area counts, + a collapsible full list
if printf '%s' "$RPT_MANY" | grep -qE '\| Area \| Files \| Changes \|' \
   && printf '%s' "$RPT_MANY" | grep -qE '`alpha/` \| 5' \
   && printf '%s' "$RPT_MANY" | grep -qi '<details><summary>All 15 files'; then
  pass "report: many files grouped by area + collapsible full list"
else
  fail "report: many files grouped by area + collapsible full list"
fi

# 10b.12 — a small diff stays a plain per-file table (no area grouping, no <details>)
(
  cd "$RPT_G" && echo y > alpha/f1.txt && git add -A && git commit -q -m small
)
RPT_FEW="$(cd "$RPT_G" && TRACK_BASE_REF=HEAD~1 RUNS_DIR=runs bash "$REPORT" R-none 2>&1 || true)"
if printf '%s' "$RPT_FEW" | grep -qE '\| File \| Change \|' \
   && ! printf '%s' "$RPT_FEW" | grep -qi '<details'; then
  pass "report: small diff renders a plain per-file table (no grouping)"
else
  fail "report: small diff renders a plain per-file table (no grouping)"
fi
rm -rf "$RPT_G"

# ---------------------------------------------------------------------------
# SUITE 11 -- SKILL.md + track-hooks.json structural integrity
# ---------------------------------------------------------------------------
section "SKILL.md + hooks structural integrity"
SKILL_MD="$SCRIPT_DIR/../SKILL.md"
HOOKS_JSON="$SCRIPT_DIR/../templates/track-hooks.json"

# 10.1 — all expected scripts exist
EXPECTED_SCRIPTS=(
  track-guard.sh track-preflight.sh track-reconcile.sh
  track-evidence.sh track-evidence-gate.sh
  track-meter.sh track-trace.sh track-sentinel.sh track-notify.sh track-report.sh
)
_all_exist=1
for _s in "${EXPECTED_SCRIPTS[@]}"; do
  [ -f "$SCRIPTS_DIR/$_s" ] || { _all_exist=0; break; }
done
[ "$_all_exist" -eq 1 ] \
  && pass "struct: all bundled scripts exist in scripts/" \
  || fail "struct: all bundled scripts exist in scripts/"

# 10.2 — track-hooks.json is valid JSON
jq empty "$HOOKS_JSON" 2>/dev/null \
  && pass "struct: track-hooks.json is valid JSON" \
  || fail "struct: track-hooks.json is valid JSON"

# 10.3 — preToolUse wires track-guard.sh
jq -e '[.hooks.preToolUse[]?.bash] | map(test("track-guard")) | any' \
    "$HOOKS_JSON" >/dev/null 2>&1 \
  && pass "struct: preToolUse -> track-guard.sh" \
  || fail "struct: preToolUse -> track-guard.sh"

# 10.4 — sessionStart wires track-reconcile.sh
jq -e '[.hooks.sessionStart[]?.bash] | map(test("track-reconcile")) | any' \
    "$HOOKS_JSON" >/dev/null 2>&1 \
  && pass "struct: sessionStart -> track-reconcile.sh" \
  || fail "struct: sessionStart -> track-reconcile.sh"

# 10.5 — postToolUse wires both track-evidence.sh and track-meter.sh
jq -e '[.hooks.postToolUse[]?.bash] | map(test("track-evidence[^-]|track-evidence\\.")) | any' \
    "$HOOKS_JSON" >/dev/null 2>&1 \
  && pass "struct: postToolUse -> track-evidence.sh" \
  || fail "struct: postToolUse -> track-evidence.sh"
jq -e '[.hooks.postToolUse[]?.bash] | map(test("track-meter")) | any' \
    "$HOOKS_JSON" >/dev/null 2>&1 \
  && pass "struct: postToolUse -> track-meter.sh" \
  || fail "struct: postToolUse -> track-meter.sh"

# 10.6 — stop wires evidence-gate AND sentinel
jq -e '[.hooks.stop[]?.bash] | map(test("track-evidence-gate")) | any' \
    "$HOOKS_JSON" >/dev/null 2>&1 \
  && pass "struct: stop -> track-evidence-gate.sh" \
  || fail "struct: stop -> track-evidence-gate.sh"
jq -e '[.hooks.stop[]?.bash] | map(test("track-sentinel")) | any' \
    "$HOOKS_JSON" >/dev/null 2>&1 \
  && pass "struct: stop -> track-sentinel.sh" \
  || fail "struct: stop -> track-sentinel.sh"

# 10.7 — evidence-gate fires before sentinel in stop array (order matters)
_gate_idx=$(jq '[.hooks.stop[]?.bash] | to_entries
  | map(select(.value | test("track-evidence-gate"))) | .[0].key // 99' \
  "$HOOKS_JSON" 2>/dev/null)
_sentinel_idx=$(jq '[.hooks.stop[]?.bash] | to_entries
  | map(select(.value | test("track-sentinel"))) | .[0].key // 99' \
  "$HOOKS_JSON" 2>/dev/null)
[ "${_gate_idx:-99}" -lt "${_sentinel_idx:-99}" ] 2>/dev/null \
  && pass "struct: stop order — evidence-gate before sentinel" \
  || fail "struct: stop order — evidence-gate before sentinel (gate=${_gate_idx} sentinel=${_sentinel_idx})"

# 10.8 — SKILL.md defines all 8 pipeline steps in order (by first-occurrence line number)
_STEPS=("1\." "2\." "3\." "4\." "5\." "6\." "7\." "8\.")
_steps_ok=1; _prev=0
for _step in "${_STEPS[@]}"; do
  _ln=$(grep -n "^\s*${_step}" "$SKILL_MD" 2>/dev/null | head -1 | cut -d: -f1)
  if [ -z "$_ln" ] || [ "$_ln" -le "$_prev" ] 2>/dev/null; then _steps_ok=0; break; fi
  _prev=$_ln
done
[ "$_steps_ok" -eq 1 ] \
  && pass "struct: SKILL.md defines Steps 1-8 in correct order" \
  || fail "struct: SKILL.md defines Steps 1-8 in correct order"

# 10.9 — Skill-per-step map references all required superpower skills
_REQUIRED_SKILLS=(
  "using-git-worktrees"
  "dispatching-parallel-agents"
  "requesting-code-review"
  "subagent-driven-development"
  "verification-before-completion"
)
_skills_ok=1
for _sk in "${_REQUIRED_SKILLS[@]}"; do
  grep -q "$_sk" "$SKILL_MD" 2>/dev/null || { _skills_ok=0; break; }
done
[ "$_skills_ok" -eq 1 ] \
  && pass "struct: SKILL.md references all required superpower skills" \
  || fail "struct: SKILL.md references all required superpower skills"

# 10.10 — Every script named in track-hooks.json exists in scripts/
_missing=0
while IFS= read -r _scr; do
  [ -z "$_scr" ] && continue
  [ -f "$SCRIPTS_DIR/$_scr" ] || _missing=$((_missing+1))
done < <(jq -r '.. | strings | select(test("track-")) | gsub(".*/"; "")' "$HOOKS_JSON" 2>/dev/null | sort -u)
[ "$_missing" -eq 0 ] \
  && pass "struct: all scripts in track-hooks.json exist in scripts/" \
  || fail "struct: $_missing scripts in track-hooks.json missing from scripts/"

# 10.11 — pr-body template exists and defines the two-zone (Auto / Asserted) contract
PR_BODY_TMPL="$SCRIPT_DIR/../templates/pr-body.md"
if [ -f "$PR_BODY_TMPL" ] \
   && grep -q '{{AUTO_BLOCK}}' "$PR_BODY_TMPL" \
   && grep -qi 'Asserted' "$PR_BODY_TMPL"; then
  pass "struct: templates/pr-body.md defines Auto + Asserted zones"
else
  fail "struct: templates/pr-body.md defines Auto + Asserted zones"
fi

# 10.12 — SKILL.md Step 8 wires the report script + pr-body template
if grep -q 'track-report.sh' "$SKILL_MD" 2>/dev/null \
   && grep -q 'templates/pr-body.md' "$SKILL_MD" 2>/dev/null; then
  pass "struct: SKILL.md Step 8 references track-report.sh + pr-body.md"
else
  fail "struct: SKILL.md Step 8 references track-report.sh + pr-body.md"
fi

# 10.13 — scaffold-mode.md guards against speculative structure (the .gitkeep-sprawl fix)
SCAFFOLD_MD="$SCRIPT_DIR/../references/scaffold-mode.md"
if grep -qi 'speculative structure' "$SCAFFOLD_MD" 2>/dev/null \
   && grep -qi 'task-declared surface' "$SCAFFOLD_MD" 2>/dev/null \
   && grep -qi '\.gitkeep' "$SCAFFOLD_MD" 2>/dev/null; then
  pass "struct: scaffold-mode.md guards against speculative structure / .gitkeep sprawl"
else
  fail "struct: scaffold-mode.md guards against speculative structure / .gitkeep sprawl"
fi

# 10.14 — SKILL.md gotchas cover speculative-structure + report-from-output
if grep -qi 'no speculative structure' "$SKILL_MD" 2>/dev/null \
   && grep -qi 'Report state from command output' "$SKILL_MD" 2>/dev/null; then
  pass "struct: SKILL.md gotchas cover speculative-structure + narration-before-action"
else
  fail "struct: SKILL.md gotchas cover speculative-structure + narration-before-action"
fi

# 10.15 — SKILL.md Step 8 wires the compliance-warnings gate
if grep -qi 'Compliance warnings' "$SKILL_MD" 2>/dev/null; then
  pass "struct: SKILL.md Step 8 wires the compliance-warnings check"
else
  fail "struct: SKILL.md Step 8 wires the compliance-warnings check"
fi

# 10.16 — pr-body.md steers the Asserted zone toward tables (Task→files→intent + compliance)
if grep -qi 'Task | Files' "$PR_BODY_TMPL" 2>/dev/null \
   && grep -qi 'What it adds' "$PR_BODY_TMPL" 2>/dev/null \
   && grep -qi 'How it.s enforced' "$PR_BODY_TMPL" 2>/dev/null \
   && grep -qi 'NEVER escaped' "$PR_BODY_TMPL" 2>/dev/null; then
  pass "struct: pr-body.md steers Asserted zone to tables (Task→files→intent) + warns vs escaped backticks"
else
  fail "struct: pr-body.md steers Asserted zone to tables (Task→files→intent) + warns vs escaped backticks"
fi

# 10.18 — pr-body.md keeps evidence canonical in the auto block; Asserted Verification is fallback-only
if grep -qi 'Evidence has ONE canonical home' "$PR_BODY_TMPL" 2>/dev/null \
   && grep -qi 'Check | Command | Result' "$PR_BODY_TMPL" 2>/dev/null \
   && grep -qi 'ONLY when the auto block shows' "$PR_BODY_TMPL" 2>/dev/null; then
  pass "struct: pr-body.md keeps evidence canonical in auto block, Asserted Verification is fallback-only"
else
  fail "struct: pr-body.md keeps evidence canonical in auto block, Asserted Verification is fallback-only"
fi

# 10.17 — governance is pushed to the MAKER (fan-out), not only the checker/review
STORY_MD="$SCRIPT_DIR/../references/story-mode.md"
REFACTOR_MD="$SCRIPT_DIR/../references/refactor-mode.md"
if grep -qi 'maker. obligation' "$SKILL_MD" 2>/dev/null \
   && grep -qi 'maker obligation' "$SCAFFOLD_MD" 2>/dev/null \
   && grep -qi 'maker obligation' "$STORY_MD" 2>/dev/null \
   && grep -qi 'maker obligation' "$REFACTOR_MD" 2>/dev/null; then
  pass "struct: governance brief pushed to fan-out makers in all three cores"
else
  fail "struct: governance brief pushed to fan-out makers in all three cores"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
TOTAL=$((PASS + FAIL + SKIP))
printf '\n===============================================\n'
printf '  single-branch-development  test suite\n'
printf '  Date:   %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
printf '  Branch: %s\n' "$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
printf '  Total: %d   passed: %d   failed: %d   skipped: %d\n' \
  "$TOTAL" "$PASS" "$FAIL" "$SKIP"
printf '===============================================\n'
if [ "$FAIL" -gt 0 ]; then
  printf '\nFailed:\n%b\n' "$FAILURES"
  exit 1
fi
exit 0
